#!/bin/bash

##Comando para instalar o OpenJDK 11##
sudo apt install default-jdk

##Dowload da IDE Eclipse##
wget -c https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2021-06/R/eclipse-jee-2021-06-R-linux-gtk-x86_64.tar.gz&mirror_id=576

##Dowload do Postman##
wget -c https://dl.pstmn.io/download/latest/linux64

##Dowload VS Code##
wget -c https://code.visualstudio.com/docs/?dv=linux64_deb
